language: go
go:
  - 1.9.2
  - master
script:
  - sh build.sh
before_deploy: "echo 'before_deploy'"
deploy:
  provider: releases
  api_key:
    secure: AK+IvwQcKY9hncm3/at9mfLRCod9Ip4UgtZ0To0lTSo2+xM2TGRT2LVvb9FyKhTdivrxfRCwS7yCjYKc1hip85zAj+lXJ2q62y024pLa9nLpU8Ia5WrGODGkV/yFNTIncrVofA73sXf84jChSpWgCyfkcWd/1K7pc2Fpay/fFqIHcIqMruQOV9wYYj7J+M0wCcgVt4TEl5hXWhouLbHKwu8j4phssAZVkjSMtyk0IAN+pCVII/WPgCBHq/g8sinsx0dwkMtMGcaem/0X2U+v9dJxeosmxkpmGIZ3Dc2oDTpIPJgu0HB1lbA4LFb5JkXv7cRTIya24RSUfl90wP4Hqwa/cY2kdBLISBxIaJxQTrPaknRIpf2YLvk8Pu54LXyWoENvJO06f34nYqa+M+KBIZB0h9BkWZ8MgqBxAOaRncRsekr6OVIz3xKrvmc5+9iVlb+UqK9Zx6i7EGEclg1w6Xc6JWAnDKVeNG3JKUxeLPQaRYYy9stwWkT6b8JIexFtHDnste5nLqjUtBDbleO0+nlZ3bSg8JXT7WKLbbNQCrBosr/V6iIoucY4eJW8t2sY+AfsnF47RbbzKOmGZWcRQz0GJ/wxkYsY9TpbgSfQ7ntHQ+RaaGGvSWr2wSiTZ7FO2aUOkrXPYH22eouxf2raufxnRr0/fN3YBou1HlDtxA0=
  file:
    - "go-api-gateway-linux-amd64"
    - "go-api-gateway-windows-amd64.exe"
    - "go-api-gateway-darwin-amd64"
  skip_cleanup: true
  on:
    tags: true
    go: 1.9.2
    repo: xuybin/go-api-gateway
after_deploy: 'curl -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"$TRAVIS_TAG\"}" -X POST https://registry.hub.docker.com/u/xuybin/go-api-gateway/trigger/$DOCKER_TOKEN/'
env:
  global:
    secure: jv43wasql/T0rzWjdk023ssX3DX2YgHcDOe/i3u7Xrh39pe+Ps8Z03NNdw7ekaUSb6BYFDFQ5kOekbspt1jZCGnrS8r4Pl6NMRAbGaRlwgLFnnd1gi8tvupQAc6dKMSWObUD0RVqaUb3WFiIWbc0JKo3J5nZANlTgyz9FGftmh7ll0Pav2+2ePLZz2SqRAcpz2SRY8g3VZ2bcr2Jtlp5TuXtsvE6sX9tsDqxOnS1tBh9pkJr3mxCy7MgMzJpDKdMGcbRpSpwHYOnkiA6L4LVxxccs1jgrywnpEE5JUzT56YdBXVUGDM7JcGbTqeCgy4v/6QbCoK07bn86X/+OyKqt9wz+z7Po2sFk4rGd9RJOBw2yfKj7xdoydOFve+6gQeYkF40gnm1eJ5vsKbPWAeG73tzybh/VK1Pw9LPZW5rZ6qOTw8cFS5LlQKMd/4apdrinZ0scNFTw581o3yp/Rs3DCcJM31dBDnJR6D4B+WO3Vs9bDfqks0bb+NEZ5IBqfg18lftBLEZwExGEryt30EP8ewDhvj1/HViW1UE6cc1zJQAzgCe/MJnLQlEf/LbagpPwXwafAPQ5bCbVypGmC8nELbWw1R0D9A+ufOXryD8l1nBTqreWoJo0cVDCITfhrrT2fR8CyhvO95bu48sFJM6ERIAfFdmV3f4x6BmeDW8uNs=
