language: go
go:
  - 1.9.2
  - master
script:
  - sh build.sh
before_deploy: "echo 'before_deploy'"
deploy:
  provider: releases
  api_key:
    secure: ApWF0vmC5NknS0lsXyuB+3IWhVO+bZkVv40qyuKQzGhkrLNOGDowWNSm/WX8iTLhcoTKS2hVfIvozr3lLh0LzIbMAMmwgATotyVa4CuAJqujDXMISapjL1VzWHI6JsBp31jstY1+NkzE2KdtZ9Amtfc1fJlPGvjy9DmPsiF8db/7jzsVE0U+Uj/rOshgTQ5dNnnGbmeqLsTFxEr0dxF+CKqhXeFqF/D/NoqRNKifvlgY4nFJ0AWQBzyCs6AibO2uwC0HVQLuILmuECD0sR/qw886sjaFzARSKNas7C8UpiOfYIZzKEvwq/v71TxII1Iad3DhtsuLVAnc/FephHfp5GbUiktpc33ryC6nJy/+N2R70sfQbnbcFiI6G9xNL8FjI989RUndsDSzMHyGX0X1YSfx7EqdiHqydd+TML3SpepHjaTLqVADzV61IjTS7LXqaDGBJU2KDwey6p7MyX9UDg5U0aCYC9BqoGTCWNkEdUo3wP2/ms716eh8X61Vrl4ZVnPX+cPpcx6cwPcOYhKNf3v4wEGBsj6GZD3L2C6N7XHA5HmQ+bJUdAf1s/BmAP1cDfvduGPrSX33Vg29IhruPPBa9Q1lLqchycEJX/b1G34U5I3HrUoSZK3OrLqJREd4xDRcqpw9HFXkevQvf4AO1bwB0AMsMnK83nBlNZSZrmk=
  file:
    - "go-api-gateway-linux-amd64"
    - "go-api-gateway-windows-amd64.exe"
    - "go-api-gateway-darwin-amd64"
  skip_cleanup: true
  on:
    tags: true
    go: 1.9.2
    repo: xuybin/go-mysql-api
after_deploy: 'curl -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"$TRAVIS_TAG\"}" -X POST https://registry.hub.docker.com/u/xuybin/go-api-gateway/trigger/$DOCKER_TOKEN/'
env:
  global:
    secure: jv43wasql/T0rzWjdk023ssX3DX2YgHcDOe/i3u7Xrh39pe+Ps8Z03NNdw7ekaUSb6BYFDFQ5kOekbspt1jZCGnrS8r4Pl6NMRAbGaRlwgLFnnd1gi8tvupQAc6dKMSWObUD0RVqaUb3WFiIWbc0JKo3J5nZANlTgyz9FGftmh7ll0Pav2+2ePLZz2SqRAcpz2SRY8g3VZ2bcr2Jtlp5TuXtsvE6sX9tsDqxOnS1tBh9pkJr3mxCy7MgMzJpDKdMGcbRpSpwHYOnkiA6L4LVxxccs1jgrywnpEE5JUzT56YdBXVUGDM7JcGbTqeCgy4v/6QbCoK07bn86X/+OyKqt9wz+z7Po2sFk4rGd9RJOBw2yfKj7xdoydOFve+6gQeYkF40gnm1eJ5vsKbPWAeG73tzybh/VK1Pw9LPZW5rZ6qOTw8cFS5LlQKMd/4apdrinZ0scNFTw581o3yp/Rs3DCcJM31dBDnJR6D4B+WO3Vs9bDfqks0bb+NEZ5IBqfg18lftBLEZwExGEryt30EP8ewDhvj1/HViW1UE6cc1zJQAzgCe/MJnLQlEf/LbagpPwXwafAPQ5bCbVypGmC8nELbWw1R0D9A+ufOXryD8l1nBTqreWoJo0cVDCITfhrrT2fR8CyhvO95bu48sFJM6ERIAfFdmV3f4x6BmeDW8uNs=
