language: go
go:
  - 1.9.2
  - master
script:
  - sh build.sh
before_deploy: "echo 'before_deploy'"
deploy:
  provider: releases
  api_key:
    secure: AK+IvwQcKY9hncm3/at9mfLRCod9Ip4UgtZ0To0lTSo2+xM2TGRT2LVvb9FyKhTdivrxfRCwS7yCjYKc1hip85zAj+lXJ2q62y024pLa9nLpU8Ia5WrGODGkV/yFNTIncrVofA73sXf84jChSpWgCyfkcWd/1K7pc2Fpay/fFqIHcIqMruQOV9wYYj7J+M0wCcgVt4TEl5hXWhouLbHKwu8j4phssAZVkjSMtyk0IAN+pCVII/WPgCBHq/g8sinsx0dwkMtMGcaem/0X2U+v9dJxeosmxkpmGIZ3Dc2oDTpIPJgu0HB1lbA4LFb5JkXv7cRTIya24RSUfl90wP4Hqwa/cY2kdBLISBxIaJxQTrPaknRIpf2YLvk8Pu54LXyWoENvJO06f34nYqa+M+KBIZB0h9BkWZ8MgqBxAOaRncRsekr6OVIz3xKrvmc5+9iVlb+UqK9Zx6i7EGEclg1w6Xc6JWAnDKVeNG3JKUxeLPQaRYYy9stwWkT6b8JIexFtHDnste5nLqjUtBDbleO0+nlZ3bSg8JXT7WKLbbNQCrBosr/V6iIoucY4eJW8t2sY+AfsnF47RbbzKOmGZWcRQz0GJ/wxkYsY9TpbgSfQ7ntHQ+RaaGGvSWr2wSiTZ7FO2aUOkrXPYH22eouxf2raufxnRr0/fN3YBou1HlDtxA0=
  file:
    - "go-api-gateway-linux-amd64"
    - "go-api-gateway-windows-amd64.exe"
    - "go-api-gateway-darwin-amd64"
  skip_cleanup: true
  on:
    tags: true
    go: 1.9.2
    repo: xuybin/go-api-gateway
after_deploy: 'curl -H "Content-Type: application/json" --data "{\"source_type\": \"Tag\", \"source_name\": \"$TRAVIS_TAG\"}" -X POST https://registry.hub.docker.com/u/xuybin/go-api-gateway/trigger/$DOCKER_TOKEN/'
env:
  global:
    secure: SG9x7SQiPxwtMuLp7ZoPrycT3/Wf4hi9WoRBXcT7+wacjaZHQQAjPm0k5qGqWzL1yxMx6Ux/E6HVNWUsj8Zavwu1s7SpbhfxhyeeXdmTRp/DecvUEyvp6upYlD1O34YaUEGOQfMTnytuMmiPKTkdAevdTj69zuwClBGjUBRjGSUZLA4hcGuwCBA73rV38kXWuZG4GHEpmFYaBvdRAJMBHXf+aHa/M4ciTzFcppNnTiPEdfMsPH0fV4pXIUZwxam/52gPn4gI/ppntRqs0co9oxtDGmZjHrBiwExBmbTSs62eBM3tmRDxbXS9bYtIXETBZEF8GnMC3BmCkkeBX9Odn92GaOEkBAOK61CsHdb8TLNxEjZKfhSco0VP2dTgwkilzEXup2GsMR6HxV4ZMFDFkl/KMYYb5K+rTBnQqQq/FiGAl+DfoijsT2KpmHC8qXiOcKjXC7FRXiQ9HrrOBHVPuaA12ZvxeK8WHKHkGO07eLWpd0UqPUEZcV8J2Su06j5Q2s8K0vyBYT+aw14ydcMqo/QEmntL0iT0SrCu2y6I0NsFCT4nA3v8mVKVbKYncSj3DJyV961YX6n/t+hPHMcvBBJ/wtE2APOC5lq/co8Hcx0DQ9DliCQSehfTkraE4Fa0GKnI9YpU2Aum6zKUmzKlg61poAbYgXuNP8mntOwH3co=
